name: Node.js CI

on:
  push:
    branches: [main, canary]
  pull_request:
    branches: [main, canary]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run type-check
      - run: npm run format
      - run: npm run lint
      - run: npm run db:integration
      - run: bash ./scripts/coverage.sh
